<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>IntegrationTests</RootNamespace>
    <AssemblyName>IntegrationTests</AssemblyName>
    <Platforms>AnyCPU;x86</Platforms>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CricketClubAccounts\CricketClubAccounts.csproj" />
    <ProjectReference Include="..\CricketClubDAL\CricketClubDAL\CricketClubDAL.csproj" />
    <ProjectReference Include="..\CricketClubDomain\CricketClubDomain.csproj" />
  </ItemGroup>

</Project>