<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>CricketClubAccounts</RootNamespace>
    <AssemblyName>CricketClubAccounts</AssemblyName>
    <Platforms>AnyCPU;x86</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CricketClubDAL\CricketClubDAL\CricketClubDAL.csproj" />
    <ProjectReference Include="..\CricketClubDomain\CricketClubDomain.csproj" />
    <ProjectReference Include="..\CricketClubMiddle\CricketClubMiddle.csproj" />
  </ItemGroup>

</Project>