name: Promote to Prod

on:
  workflow_call:
    inputs:
      sha_list:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      sha:
        type: choice
        description: "Select a build to promote"
        options: []

jobs:
  promote:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Convert SHA list into dropdown
        id: convert
        run: |
          echo "options<<EOF" >> $GITHUB_OUTPUT
          echo "${{ inputs.sha_list }}" | jq -r '.[]' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Prod ACA
        run: |
          IMAGE="ghcr.io/grahampontin/thevillagecc-api:${{ github.event.inputs.sha }}"
          echo "Deploying image: $IMAGE"

          az containerapp update \
            --name villagecc-api \
            --resource-group Village_CC \
            --image $IMAGE \
            --registry-server ghcr.io \
            --registry-username ${{ secrets.GHCR_USERNAME }} \
            --registry-password ${{ secrets.GHCR_PAT }}

      - name: Show latest revision
        run: |
          az containerapp revision list \
            --name villagecc-api \
            --resource-group Village_CC \
            --query "[?active].{revisionName:name,image:template.containers[0].image}"
